IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'status' AND TABLE_SCHEMA = 'dbo')
BEGIN
    create table status (
		id BIGINT IDENTITY(1,1) PRIMARY KEY,
		title VARCHAR (50) NOT NULL UNIQUE
	);
END
